# -*- coding: utf-8 -*-
"""Resume analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoHSyzqw25YXGwn-eT_-QAW63JS4j4_H
"""

!pip install streamlit pyngrok pdfplumber

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pdfplumber
# import re
# 
# st.title("📄 Ravi Resume Analyzer ")
# 
# 
# # Upload resume
# uploaded_file = st.file_uploader("Upload your Resume (PDF only)", type=["pdf"])
# 
# def extract_text(file):
#     text = ""
#     with pdfplumber.open(file) as pdf:
#         for page in pdf.pages:
#             text += page.extract_text() or ""
#     return text
# 
# def analyze_resume(text):
#     score = 0
#     feedback = []
# 
#     # Skills check
#     skills = ["python", "java", "c++", "machine learning", "data analysis"]
#     found_skills = [skill for skill in skills if skill in text.lower()]
# 
#     score += len(found_skills) * 10
# 
#     if found_skills:
#         feedback.append(f"✅ Skills found: {', '.join(found_skills)}")
#     else:
#         feedback.append("❌ No relevant skills found")
# 
#     # Email check
#     if re.search(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-z]{2,}", text):
#         score += 10
#         feedback.append("✅ Email found")
#     else:
#         feedback.append("❌ Email missing")
# 
#     # Phone check
#     if re.search(r"\b\d{10}\b", text):
#         score += 10
#         feedback.append("✅ Phone number found")
#     else:
#         feedback.append("❌ Phone number missing")
# 
#     return score, feedback
# 
# if uploaded_file:
#     text = extract_text(uploaded_file)
# 
#     st.subheader("📃 Extracted Text")
#     st.write(text[:1000])  # preview
# 
#     score, feedback = analyze_resume(text)
# 
#     st.subheader("📊 Resume Score")
#     st.success(f"Score: {score}/100")
# 
#     st.subheader("💡 Feedback")
#     for item in feedback:
#         st.write(item)

!streamlit run app.py &>/content/logs.txt &

!ngrok config add-authtoken 3AExYWxtozmPyQVM39382LMU8MM_36KdkxThk8eq7MfXhzYUe

from pyngrok import ngrok

public_url = ngrok.connect(8501)
print(public_url)